global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'scrapper'
    static_configs:
      - targets: ['localhost:8082']
  - job_name: 'bot'
    static_configs:
      - targets: ['localhost:8083']
