app:
  test: This is scrapper application
  scheduler:
    interval: 10000

springdoc:
  swagger-ui:
    path: /swagger-ui

spring:
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: 123456
