version: '3.9'

services:
  postgresql:
    image: postgres:15
    container_name: postgres_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: scrapper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      - postgresql
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/scrapper
      - --username=postgres
      - --password=123456
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4:6
    container_name: pgadmin_container
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: mail@mail.com
      PGADMIN_DEFAULT_PASSWORD: 12345678
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - backend

networks:
  backend:

volumes:
  postgres-data:
  pgadmin-data: