name: Build bot

on:
  pull_request:
    paths:
      - 'bot/**'
  push:
    branches:
      - 'main'
    paths:
      - 'bot/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: Add bot token
        run: | 
          sed -i 's/\${BOT_TOKEN}/$BOT_TOKEN/g' ./bot/src/main/resources/application.yml
        env:
            BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

      - run: echo ${{ secrets.BOT_TOKEN }}

      - name: Maven Package
        run: mvn package -pl bot -am

      - name: Build docker image
        run: docker build -t bot:latest ./bot/
