name: Build scrapper

on:
  pull_request:
    branches:
      - '*'
    paths:
      - 'scrapper/**'
  push:
    branches:
      - 'main'
    paths:
      - 'scrapper/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven
      - name: Maven Package
        run: mvn package -pl scrapper -am